install:
  # - ps: Install-Product node 4
  # - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein.bat
  # - chmod a+x lein.bat
  # - lein self-install
    - set

test_script: 
  - lein test

build: off