install:
  - ps: Install-Product node 4
  - cmd: $source = "https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein.bat"
  - cmd: $destination = %APPDATA%\lein.bat
  - cmd: Invoke-WebRequest $source -OutFile $destination
  - set PATH=$destination;%PATH%
  - chmod a+x lein.bat
  - lein self-install

test_script: 
  - lein test

build: off