install:
  - ps: Install-Product node 4
  - ps: Start-FileDownload 'https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein.bat'
  - cmd: move lein.bat %APPDATA%
  - set PATH=%APPDATA%\lein.bat;%PATH%
  - chmod a+x lein.bat
  - lein self-install

test_script: 
  - lein test

build: off